- name: Cisco Secure ADC + VMWare Provisioning 
  hosts: localhost
  connection: local
  gather_facts: true
 
  vars_files:
    - vars.yaml

  tasks:
  - name: Change power state of Cisco Secure ADC
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      uuid: "{{ adcvm_uuid }}"
      datacenter: "{{ adcvm_datacenter }}"
      state: poweredoff
