- name: Cisco Secure ADC VA Provisioning 
  hosts: localhost
  connection: local
  gather_facts: true
 
  vars_files:
    - vars.yaml

  tasks:
  - name: Create an ADC from Template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ adcvm_datacenter }}"
      template: "{{ adcvm_template }}"
      name: CiscoADC-01
      folder: "{{ adcvm_folder }}"
      datastore: "{{ adcvm_datastore }}"

      # The following are needed if DRS is configured
      # resource_pool: 
      # cluster: 
